<Content>
    orientation: "vertical"
    spacing: "12dp"
    size_hint_y: None
    height: "100dp"

    MDLabel:
        markup: True
        text: 'Acesse [ref=url][u][color=#00aaaa]http://localhost:5000/auth/twitch[/color][/u][/ref] para fazer a autenticação:'
        font_size: 18
        theme_text_color: "Primary"
        #adaptive_width: True
        size: self.texture_size
        on_ref_press: wb.open("http://localhost:5000/auth/twitch")
